version: '3.8'


services:
  web:
    build: .
    image: grphql
    container_name: grphql_con
    command: "sh -c '
    python manage.py makemigrations && 
    python manage.py migrate && 
    python manage.py runserver 0.0.0.0:8012'"
    ports:
      - '8012:8012'
    depends_on:
      - db
  db:
    image: postgres:alpine
    container_name: pg6
    restart: always
    ports:
      - '5437:5432'
    environment:
      POSTGRES_PASSWORD: 1
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

