# Generated by Django 5.2.4 on 2025-07-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
