# Generated by Django 5.2.4 on 2025-07-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('old', 'Old')], default='new', max_length=100),
        ),
    ]
